### ISSUE TITLE
ignoring ids

### ISSUE THREAD

**Issue by phamdt** [tschortsch/gulp-bootlint#15]
it'd be helpful if there were ways to conditionally disable ids. for example, W001 complains about the missing <head> tag on partials that naturally would not need/have a <head> tag. however, for any page that is a template that includes various partials, i would want it to complain.

**Comment by tschortsch** [comment]
I agree, but I think it would make sense to do this condition on a task-level like the following:
```
gulp.task('bootlint-template', function() {
    return gulp.src('./templates/*.html')
        .pipe(bootlint());
});
gulp.task('bootlint-partials', function() {
    return gulp.src('./templates/partials/*.html')
        .pipe(bootlint({
            disabledIds: ['W001'],
        }));
});
gulp.task('bootlint', ['bootlint-template', 'bootlint-partials']);
```

What do you think?

**Comment by phamdt** [comment]
ya, that works
