### ISSUE TITLE
Feature request: Add support for Boostrap 4

### ISSUE THREAD

**Issue by cebreus** [tschortsch/gulp-bootlint#18]
For example:

1) Missing support for form row `.form-row`. This is valid:
```
<div class="form-row">
    <div class="form-group col-md-4">
```

2) Missing support for `.col-auto`. This is valid:
```
<div class="form-row">
    <div class="col-auto">
```

**Comment by tschortsch** [comment]
Hi @cebreus. Thanks for your feature request but since this is just a gulp wrapper around Bootlint (https://github.com/twbs/bootlint) it only supports whatever Bootlint supports. Please create an issue on that repository.
