### ISSUE TITLE
Add Dependabot to help keep deps up-to-date?

### ISSUE THREAD

**Issue by coliff** [tschortsch/gulp-bootlint#20]
Some of the dependencies are out of date. Maybe could add Dependabot to open PRs where necessary?

https://github.com/marketplace/dependabot-preview

REF: https://david-dm.org/tschortsch/gulp-bootlint

**Comment by tschortsch** [comment]
@coliff You're right. I'll try to release a new version this week with updated dependencies.

**Comment by tschortsch** [comment]
I just released [v0.11.0](https://github.com/tschortsch/gulp-bootlint/releases/tag/v0.11.0) of the package. I had to drop support for Node.js versions <7.x. Hopefully this is not a problem for you.

**Comment by coliff** [comment]
Thanks for the update! Yep, it’s good you dropped support for Node.JS <7.x - those aren’t supported anymore anyway.
