### ISSUE TITLE
Update to Bootlint v1.0.0

### ISSUE THREAD

**Issue by coliff** [tschortsch/gulp-bootlint#22]
Bootlint is now 1.0.0!
https://github.com/twbs/bootlint/releases

Could you please make a new release?

**Comment by tschortsch** [comment]
Thanks for the hint. I just started with a pull request for that: https://github.com/tschortsch/gulp-bootlint/pull/24. Will try to release a new version as soon as possible

**Comment by tschortsch** [comment]
Version 1.0.0 of the plugin has been released: https://github.com/tschortsch/gulp-bootlint/releases/tag/v1.0.0

**Comment by coliff** [comment]
awesome! thanks for the quick turnaround. :-)
