### ISSUE TITLE
Bootlint 1.1.0

### ISSUE THREAD

**Issue by coliff** [tschortsch/gulp-bootlint#28]
hi there. would you be able to publish an update with bootlint v1.1.0? thanks!
https://github.com/twbs/bootlint/releases/tag/v1.1.0

**Comment by tschortsch** [comment]
Thanks for the hint. I just published v1.1.0 of the package which includes bootlint 1.1.0: https://github.com/tschortsch/gulp-bootlint/releases/tag/v1.1.0
